name: phabricator
authors:
- "Kenneth Endfinger <kaendfinger@gmail.com>"
homepage: https://github.com/SpinlockLabs/phabricator.dart
description: Phabricator Client
version: 0.1.0
environment:
  sdk: ">=1.8.0 <3.0.0"
